version: '3'
services:

  app:
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
 
volumes:
  mongodb_data_container:
